version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./back:/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./front:/app
    environment:
      - NODE_ENV=production
