name: Main PR CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
          cache-dependency-path: './front/package-lock.json'
      - run: npm ci
      - run: npm run build      

  back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
          cache-dependency-path: './back/package-lock.json'
      - run: npm ci
