name: Main PR CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
          cache-dependency-path: './front/package-lock.json'
      - run: npm ci
      - run: npm run build      

  back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
          cache-dependency-path: './back/package-lock.json'
      - run: npm ci
      - run: npm run build

  sonarcloud:
    runs-on: ubuntu-latest
    steps:     
      - name: SonarCloud Scan
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization
