name: Main CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  front:
    runs-on: ubuntu-latest
		env:
      working-directory: ./front
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - run: npm run build
        working-directory: ${{env.working-directory}}
  back:
    runs-on: ubuntu-latest
		env:
      working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - run: npm run build
        working-directory: ${{env.working-directory}}